site :opscode

metadata

cookbook 'application_nodejs', git: 'https://github.com/ripple/cookbook-application_nodejs.git', branch: 'develop'

group :test do
  # ubuntu support cookbooks
  cookbook 'apt'
  # centos support cookbooks
  cookbook 'yum'
  # metatest support cookbooks
  cookbook 'minitest-handler'
  # test environment setup cookbook
  cookbook 'ripple-blobvault-test', :path => './test/cookbook'
end
